import { AppDataSource } from '../../infrastructure/database/data-source';
import { JournalEntry } from '../../domain/entities/JournalEntry';
import { LedgerEntry } from '../../domain/entities/LedgerEntry';
import { Voucher, VoucherType } from '../../domain/entities/Voucher';
import { Account } from '../../domain/entities/Account';
import { In } from 'typeorm';

export class DeleteJournalEntryUseCase {
  async execute(journalEntryId: string): Promise<{ success: boolean }> {
    return AppDataSource.transaction(async (em) => {
      // 1. Fetch the journal entry to make sure it exists
      const je = await em.findOne(JournalEntry, { 
        where: { id: journalEntryId },
        relations: ['ledgerEntries']
      });
      if (!je) throw new Error('Journal entry not found.');

      // 2. Fetch the voucher header
      const voucher = await em.findOne(Voucher, { where: { id: je.voucherId } });
      if (!voucher) throw new Error('Voucher header not found.');

      // 2.1 Only allow deletion of manual journals from here.
      // System-generated journals (Sales, Cash, etc.) have complex cleanup logic.
      if (voucher.type !== VoucherType.JOURNAL) {
        throw new Error(`This journal was generated by a ${voucher.type} voucher. Please delete it from its original module to ensure data consistency.`);
      }

      // 3. Validate freeze dates for all accounts involved
      const accountIds = Array.from(new Set(je.ledgerEntries.map((l) => l.accountId)));
      const accountRepo = em.getRepository(Account);
      const accounts = await accountRepo.find({ where: { id: In(accountIds) } });

      for (const account of accounts) {
        Account.validateFreezeDate(account, voucher.entryDate);
      }

      // 4. Delete ledger entries
      const ledgerRepo = em.getRepository(LedgerEntry);
      await ledgerRepo.delete({ journalEntryId: je.id });

      // 5. Delete the journal entry itself
      await em.getRepository(JournalEntry).delete({ id: je.id });

      // 6. Delete the base Voucher
      await em.getRepository(Voucher).delete({ id: voucher.id });

      return { success: true };
    });
  }
}
