import { AppDataSource } from '../../infrastructure/database/data-source';
import { JournalEntry } from '../../domain/entities/JournalEntry';
import { LedgerEntry } from '../../domain/entities/LedgerEntry';
import { AccountingService } from '../../domain/services/AccountingService';
import { Voucher, VoucherStatus, VoucherType } from '../../domain/entities/Voucher';
import { Account } from '../../domain/entities/Account';
import { In } from 'typeorm';
import { CreateJournalEntryDTO } from './CreateJournalEntryUseCase';

export class UpdateJournalEntryUseCase {
  private readonly accountingService = new AccountingService();

  async execute(
    journalEntryId: string,
    dto: CreateJournalEntryDTO,
  ): Promise<{ success: boolean; voucherNo: string }> {
    // Business rule: minimum 2 lines (one debit, one credit)
    if (!dto.lines || dto.lines.length < 2) {
      throw new Error('A journal entry must have at least 2 ledger lines.');
    }

    return AppDataSource.transaction(async (em) => {
      // 1. Fetch the existing journal entry
      const je = await em.findOne(JournalEntry, { 
        where: { id: journalEntryId },
        relations: ['ledgerEntries']
      });
      if (!je) throw new Error('Journal entry not found.');

      // 2. Fetch the voucher header
      const voucherRepo = em.getRepository(Voucher);
      const voucher = await voucherRepo.findOne({ where: { id: je.voucherId } });
      if (!voucher) throw new Error('Voucher header not found.');

      // 2.1 Only allow updating of manual journals from here.
      if (voucher.type !== VoucherType.JOURNAL) {
        throw new Error(`This journal was generated by a ${voucher.type} voucher. Please edit it from its original module to ensure data consistency.`);
      }

      const accountRepo = em.getRepository(Account);

      // 3. Validate freeze dates for OLD accounts at the OLD date
      const oldAccountIds = Array.from(new Set(je.ledgerEntries.map((l) => l.accountId)));
      const oldAccounts = await accountRepo.find({ where: { id: In(oldAccountIds) } });
      for (const account of oldAccounts) {
        Account.validateFreezeDate(account, voucher.entryDate);
      }

      // 4. Validate freeze dates for NEW accounts at the NEW date
      const newAccountIds = Array.from(new Set(dto.lines.map((l) => l.accountId)));
      const newAccounts = await accountRepo.find({ where: { id: In(newAccountIds) } });
      for (const account of newAccounts) {
        Account.validateFreezeDate(account, dto.entryDate);
      }

      // 5. Update voucher header
      voucher.entryDate = dto.entryDate;
      voucher.narration = dto.narration;
      voucher.status = VoucherStatus.POSTED; // Journal entries are typically posted immediately
      await voucherRepo.save(voucher);

      // 6. Update JournalEntry header
      je.entryDate = dto.entryDate;
      je.narration = dto.narration;
      je.sourceReference = dto.sourceReference;
      
      // 7. Wipe and recreate ledger entries
      const ledgerRepo = em.getRepository(LedgerEntry);
      await ledgerRepo.delete({ journalEntryId: je.id });

      je.ledgerEntries = [];
      for (const line of dto.lines) {
        const le = new LedgerEntry();
        le.accountId = line.accountId;
        le.debitAmount = line.debitAmount;
        le.creditAmount = line.creditAmount;
        le.debitGold = line.debitGold;
        le.creditGold = line.creditGold;
        le.narration = line.narration;
        // Trigger validation
        le.validateSingleSide();
        je.ledgerEntries.push(le);
      }

      // 8. Validate balance
      this.accountingService.assertBalanced(je);

      // 9. Persist
      await em.save(je);

      return { success: true, voucherNo: voucher.voucherNo };
    });
  }
}
